name: kube-deploy-dev

env:
  cluster_name: "MAINCLUSTER"
  cluster_resource_group: "VIME-KUBERNETES-MAINCLUSTER"
  cluster_namespace: "vime-dev"

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: The name of the image to build / deploy
    secrets:
      container_registry_url:
        required: true
      azure_credentials:
        required: true
      container_registry_password:
        required: true
      container_registry_username:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      # Login to the azure container registry to be able to push the image
      - uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.container_registry_url }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      # Required for build-push-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.container_registry_url }}/${{ inputs.image_name }}:${{ github.sha }}
          build-args: |
            GH_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}

      # Set the target AKS cluster for the following kubernetes actions
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: "${{ env.cluster_name }}"
          resource-group: "${{ env.cluster_resource_group }}"

      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v1
        with:
          namespace: "${{ env.cluster_namespace }}"
          container-registry-url: ${{ secrets.container_registry_url }}
          container-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          secret-name: "container-registry-secret"

      - uses: Azure/k8s-deploy@v1.2
        with:
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
            kubernetes/ingress-dev.yaml
          images: |
            ${{ secrets.container_registry_url }}/${{ inputs.image_name }}:${{ github.sha }}
          imagepullsecrets: |
            container-registry-secret
          namespace: ${{ env.cluster_namespace }}