name: kube-deploy-target

env:
  cluster_name: "MAINCLUSTER"
  cluster_resource_group: "VIME-KUBERNETES-MAINCLUSTER"
  namespace_prefix: "vime-"

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: The name of the image to build / deploy
      manifests:
        required: true
        type: string
        description: The kubernetes manifests to deploy
      container_registry_url:
        required: true
        type: string
        description: The URL of the container registry the image should be stored at
    secrets:
      # required infrastructure secrets
      azure_credentials:
        required: true
      container_registry_password:
        required: true
      container_registry_username:
        required: true
      gh_access_token:
        required: true
      # application secrets, only required for some services
      secret:
        required: false
      jitsi_secret:
        required: false
      database_url:
        required: false
      sendinblue_api_key:
        required: false

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Select correct github tag
        id: tag_selector
        env:
          GITHUB_TOKEN: ${{ secrets.gh_access_token }} # this secret is automatically populated by GHA
        run: |
          if [ ${{ github.event.inputs.version }} = 'latest' ];
          then
            echo "::set-output name=tag::$(gh release view --json tagName -q .tagName)"
            echo "$(gh release view --json tagName -q .tagName)"
          else
            echo "::set-output name=tag::${{ github.event.inputs.version}}"
          fi

      # Set the target AKS cluster for the following kubernetes actions
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.azure_credentials }}"
          cluster-name: "${{ env.cluster_name }}"
          resource-group: "${{ env.cluster_resource_group }}"

      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v1
        with:
          namespace: ${{ env.namespace_prefix }}${{ inputs.target }}
          container-registry-url: ${{ inputs.container_registry_url }}
          container-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          secret-name: "container-registry-secret"

      - name: Populate runtime env vars with secrets
        uses: vivents/replace-action@master
        with:
          files: ${{ inputs.manifests }}
          replacements: |
            $SECRET=${{ secrets.secret }}
            $JITSI_SECRET=${{ secrets.jitsi_secret }}
            $DATABASE_URL=${{ secrets.database_url }}
            $SENDINBLUE_API_KEY=${{ secrets.sendinblue_api_key }}

      - uses: Azure/k8s-deploy@v1.2
        with:
          manifests: ${{ inputs.manifests }}
          images: |
            ${{ inputs.container_registry_url }}/${{ inputs.image_name }}:${{ steps.tag_selector.outputs.tag }}
          imagepullsecrets: |
            container-registry-secret
          namespace: ${{ env.namespace_prefix }}${{ github.event.inputs.target }}